# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('portal_longtitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacked_date', models.DateTimeField()),
                ('attacked_agent', models.CharField(max_length=64)),
                ('agent_level', models.IntegerField(default=0)),
                ('damaged_type', models.CharField(max_length=16)),
                ('attacker', models.CharField(max_length=64)),
                ('attacked_portal', models.CharField(max_length=128)),
                ('linked_portal', models.CharField(max_length=128)),
                ('portal_owner', models.CharField(max_length=64)),
                ('portal_address', models.CharField(max_length=256)),
                ('portal_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('portal_longtitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
