# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='portal_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='portal',
            old_name='portal_longtitude',
            new_name='longtitude',
        ),
        migrations.AddField(
            model_name='portal',
            name='portal_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
