# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_auto_20161004_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='linked_portal',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='portal_owner',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
