# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_auto_20161004_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='linked_portal',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='report',
            name='portal_owner',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
